spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expertise_system
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092